In [7]:
# list and array and numpy
r, f = 1.5, 0.5

In [9]:
n = 10
for i in range(n) :
    f=r*f*(1-f)
    print(f)

0.375
0.3515625
0.341949462890625
0.3375300415791571
0.3354052689160944
0.33436286174912516
0.3338465076480908
0.33358952546889614
0.3334613309494993
0.3333973075663317


In [10]:
f

0.3333973075663317

In [13]:
# list 필요한 데이터를 나열.
r, f = 1.5, 0.5
n= 10
fn = []
for i in range(n):
    fn.append(f)
    f=r*f*(1-f)

In [12]:
fn

[0.3333973075663317,
 0.33336531431077876,
 0.3333493222878816,
 0.33334132742713746,
 0.33333733028437706,
 0.33333533178489183,
 0.33333433255312184,
 0.33333383294172997,
 0.3333335831371573,
 0.33333345823515165]

In [14]:
x = 3
a = [1,2,3,4,5,6]
b = [3,1,4,5,6,7]





In [16]:
b[0], b[1], b[2]
b[0:3]

[3, 1, 4]

In [20]:
b[2:5]
b[:]
b[:5]
c = b

In [21]:
c

[3, 1, 4, 5, 6, 7]

In [22]:
a+b

[1, 2, 3, 4, 5, 6, 3, 1, 4, 5, 6, 7]

In [24]:
a - b # 정의안된다

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [25]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [29]:
a*x #3번 반복

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

$$리스트 수정$$

In [30]:
c = [3,2,4,1,5,9]

In [31]:
b[1]

1

In [32]:
b[1] = 2

In [34]:
b

[3, 2, 4, 5, 6, 7]

In [35]:
b[1] = 1

In [36]:
b

[3, 1, 4, 5, 6, 7]

In [37]:
b[1] = [1,2,3]

In [39]:
b

[3, [1, 2, 3], 4, 5, 6, 7]

In [40]:
b[1][2]

3

In [44]:
a = [1,4,5,6]
a[0:1]

[1]

In [42]:
a[0:1] = [1,2,3]

In [43]:
a

[1, 2, 3, 4, 5, 6]

In [45]:
a = [1,4,5,6]
a[1:1]

[]

In [46]:
a[1:1] = [2,3]

In [48]:
a
a.append(8)

In [49]:
a.append([9,10])

In [50]:
a

[1, 2, 3, 4, 5, 6, 8, [9, 10]]

배열(array) real Vector

In [55]:
a = [1,2,3,4,5]
a[1:1] = [7,7,7]

array를 쓰려면 넘파이를 써야함
python을 이용해서 여러가지를 할껀데 하나하나 다 기능을 만들면 어렵 그래서 만든 open source를 사용할거임 이것을 library라부름

In [61]:
import numpy as np

In [69]:
#array는 넘파이모듈 안에 있는 함수이다
#[]은 x값 array는 f로 생각
#array는 행렬처럼 생각
x = np.array( [1,2,3,4,5] )


In [70]:
a = [1,2,3,4,5]
b = [3,1,4,1,5]
x = np.array([1,2,3,4,5])
y= np.array([3,1,4,1,5])

In [71]:
a + b

[1, 2, 3, 4, 5, 3, 1, 4, 1, 5]

In [72]:
x+y,x-y,x*y,x/y # 각각은 calculate of vector 와 같다
#그리고 리스트 연산보다 빠르다

(array([ 4,  3,  7,  5, 10]),
 array([-2,  1, -1,  3,  0]),
 array([ 3,  2, 12,  4, 25]),
 array([0.33333333, 2.        , 0.75      , 4.        , 1.        ]))

In [75]:
np.zeros(5) #성분이 0인 차원 수 소환
.zeros(5) #성분이 0인 차원 수 소환
np.ones(10) #각각의 성분이 1인걸 만들어라

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
np.linspace(0,100,11) # 0부터 100까지 11등분

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [79]:
x + y, x-y, x*y, x/y #성분들 끼리

(array([ 4,  3,  7,  5, 10]),
 array([-2,  1, -1,  3,  0]),
 array([ 3,  2, 12,  4, 25]),
 array([0.33333333, 2.        , 0.75      , 4.        , 1.        ]))

In [80]:
x

array([1, 2, 3, 4, 5])

In [81]:
x[2] + x[0]

4

In [82]:
#elements 를 다루는 방식은 list를 다룰 때랑 같다

Matrix

In [93]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]


In [94]:
x = np.array(a)
y = np.array(b)

In [95]:
a+b

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [97]:
x+y

array([[ 6,  8],
       [10, 12]])

In [98]:
x-y

array([[-4, -4],
       [-4, -4]])

In [101]:
x*y #tensor produut 행렬 곱은 아님

array([[ 5, 12],
       [21, 32]])

In [104]:
np.dot(x,y) #행렬 곱, 내적 곱 둘다 가능

array([[19, 22],
       [43, 50]])

In [110]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [112]:
np.linalg.inv(x) # 역행렬

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [114]:
np.linalg.det(x)

-2.0000000000000004

In [115]:
import math

In [118]:
math.pi #파이

3.141592653589793

In [120]:
math.exp(1)#expernancial

2.718281828459045

In [124]:
math.log(10) #밑이 e인 자연로그

2.302585092994046

In [134]:
math.sin(1) #안에 라디안 단위로 들어가야함

0.8414709848078965

In [135]:
math.cos(0)

1.0

함수

In [150]:
#programming 함수는 같다
def fk(m,n) :
    a = 3*m+4*n
    return a

fk(2,6)

30

함수

In [152]:
#Factorial

def facto(x) :
     f,n = 1,1
     while(n <= x) :
         f = f*n
         n = n+1
     return f

In [154]:
for i in range(11):
    print(facto(i))

1
1
2
6
24
120
720
5040
40320
362880
3628800


In [162]:
def falling(t) :
    g = 9.8
    x = 0.5*g*(t**2)
    return [x,t]

In [163]:
falling(4)

[78.4, 4]